# Settings
MIN_DENSE_SIZE = 1
MAX_DENSE_SIZE = 100
MIN_CONV_FILTERS = 1
MAX_CONV_FILTERS = 10
MIN_CONV_KERNEL_SIZE = 2
MAX_CONV_KERNEL_SIZE = 10
MIN_CONV_STRIDE = 1
MAX_CONV_STRIDE = 3
POOLING_PROBABILITY = 0.4
MIN_POOL_SIZE = 2
MAX_POOL_SIZE = 5
MAX_POOL_STRIDE_OVERLAP = 5
ACTIVATIONS = ['relu', 'sigmoid', 'tanh']
MUTATION_RATE = 0.2
BATCH_SIZE = 128
EPOCH_NBR = 25
